"""from_table can be null

Revision ID: 1bffaf6e84b2
Revises: e375303094f3
Create Date: 2024-03-09 08:43:43.388027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bffaf6e84b2'
down_revision = 'e375303094f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grapheme_logs', schema=None) as batch_op:
        batch_op.alter_column('from_phoneme',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grapheme_logs', schema=None) as batch_op:
        batch_op.alter_column('from_phoneme',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
