"""graphemes

Revision ID: e375303094f3
Revises: 
Create Date: 2024-03-08 15:40:28.717695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e375303094f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grapheme', sa.String(), nullable=False),
    sa.Column('phoneme', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grapheme')
    )
    op.create_table('grapheme_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grapheme_id', sa.Integer(), nullable=True),
    sa.Column('grapheme_name', sa.String(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.Column('from_phoneme', sa.String(), nullable=False),
    sa.Column('to_phoneme', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['grapheme_id'], ['graphemes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grapheme_logs')
    op.drop_table('graphemes')
    # ### end Alembic commands ###
